Lab 5
zaikin123/Labs pull request #1
Opened 2018-11-17 17:15 UTC by zaikin123

1. З чисел Фібоначі в інтервалі від 1 до 100 визначити тільки прості числа, а також їх порядкові номери в ряду Фібоначі.

2018-11-17 17:19 UTC, zaikin123 commented
@nechaido Lab#5 IP-82 Zaikin Nikita
З чисел Фібоначі в інтервалі від 1 до 100 визначити тільки прості числа, а також їх порядкові номери в ряду Фібоначі.

2018-11-18 12:54 UTC, nechaido requested changes
Необхідно виводити лише прості числа.

2018-12-13 12:50 UTC, nechaido commented
Где исправление?

2018-12-19 14:26 UTC, zaikin123 commented
@nechaido Все исправил, простите)

2018-12-23 20:10 UTC, nechaido approved these changes
Принято.

2019-01-29 10:52 UTC, closed without merging